### ISSUE TITLE
Explanation for extrinsics being changed during undistortion

### ISSUE THREAD

**Issue by s1ddok** [agisoft-llc/metashape-scripts#94]
I noticed that in a newer version of 3DGS export script, undistortion affect extrinsics. You can look [here](https://github.com/agisoft-llc/metashape-scripts/blob/b26f56826051f718358fb0626fac31e286af0451/src/export_for_gaussian_splatting.py#L316). Maybe it would be useful to provide some details/explanation for why it is the way and why it works? I've been using the old version and never had any issues with it, so I'm trying to understand which version to keep using

**Comment by PolarNick239** [comment]
Hi, undistortion includes the cropping stage (see [illustration here](https://github.com/agisoft-llc/metashape-scripts/issues/87#issuecomment-2214027520)), in case of large non-zero cx/cy (i.e. strongly shifted optical axis - see green cross below) and due to the fact that cx/cy is not supported in the colmap camera model (used by GS) - we need to shift the image so that the green cross is in the center of the image (i.e. we mimic the colmap camera model where cx/cy=0):

![image](https://github.com/user-attachments/assets/da993119-ce6c-4dab-af86-705ef150bda4)

But in such case the image will be VERY cropped (leading to high information loss) - look at small red solid rectangle (instead of a large dotted rectangle). To mitigate this, we rotate the camera so that we mimic the colmap camera model with cx/cy=0 but the cropped rectangle still be large in such case (and thus the loss of information due to cropping is small).

> I've been using the old version and never had any issues with it, so I'm trying to understand which version to keep using

If you are already getting good results, the cx/cy value is probably low in your case, so the difference due to this script update will be small. But as always, try to process using the new script and compare the result with the old one to see which works better - and stick with it.

**Comment by PolarNick239** [comment]
The accuracy should be similar. So in general you can just use the new script (and that's why it was updated this way instead of adding the optional "rotate camera to compensate for cx/cy" checkbox).

But the most reliable is to compare the results before/after. So please let me know if you got a noticeable degradation of results.

**Comment by s1ddok** [comment]
So I've spent quite some time with the new script and results are quite strange:

1. I'm using compute_undistorted_calib from the script elsewhere and with the new algo I'm getting a much better reprojection error, much faster, though I think the values are wrong because it doesn't take into account new T1 transform
2. New image undistorted has several problems:
  - First of all, it creates black undistortion padding on some photos instead of cropping them. Honestly, previous version also did this sometimes, but not as often as this new one.
  ![image](https://github.com/user-attachments/assets/3629e4b7-7d9b-43f8-8f5a-5a92577b160c)
  - Secondly, it consistently crashed with "Bad allocation" error until I wrapper `image().warp` into `try: except:` block and found out that it crashes for 10% of images. 

do you think this can be addressed? cc @Vineg as an author of recent changes

also, I've tried to uncomment check undisttorted calib method and it also crashed with "pt.x None type does not have .x"

**Comment by PolarNick239** [comment]
Please share a data-reproducer to support@agisoft.com with steps to reproduce, so we were able to reproduce and investigate the problem. Probably small part of the dataset will be enough - just make sure that it can reproduce the problem.

**Comment by s1ddok** [comment]
Sent 🙌

**Comment by PolarNick239** [comment]
Got the data, thanks, we'll reproduce and analyze it.

**Comment by Vineg** [comment]
Hi, @s1ddok

I've checked the data and noticed very high radial distortion coefficients for some cameras (10 to 300 for k2 and k3 while typical values are -2 to 2). It is likely because there is not enough tie points closer to the edges and thus area far from the image center have very high distortion estimation error.

Could you, please, try to run Tools / Optimize Cameras with checked "Adaptive camera model fitting" before export?
This checkbox is also available for Align Photos under the Advanced options.

**Comment by s1ddok** [comment]
@Vineg I can, but I think that case should still be handled by the script? it should be possible to calculate crop rect so that there will be no black padding?

also, I think the bigger problem is warping crashing during the process, even though RE is reported to be 1.29, my guess is this is because the script fails to check broken calibs before initiating warping

**Comment by Vineg** [comment]
Hi, @s1ddok

Added a check to the script. The problem is that unproject method does not converge for such a large distortion estimates.
Now invalid parts of calibration are excluded, but I think it is still better to more accurately handle calibration using adaptive camera model fitting or making k2, k3 parameters fixed in Camera Calibration in Tools menu.
With broken calibration you may loose some useful area of an image.

**Comment by s1ddok** [comment]
checked it on the same dataset:

black padding seem to be gone, but warping is still failing on two images, doesn't work without try:except: block, I think something is still missing to be able to catch bad calibs, do you have any ideas?

**Comment by s1ddok** [comment]
![image](https://github.com/user-attachments/assets/d0ada4b0-5f50-48a1-af2d-f14789c0ad45)

correction: found a very minor black padding, might be precision error, but maybe some imprefections in detecting bad calibs/calculating crops.

**Comment by Vineg** [comment]
@s1ddok 
I was not able to reproduce bad_alloc / black padding on the data you've sent. It would be good if you tell camera names with problems and attach a file with a log.

I've added a little border for broken calibs, it may fix the problem.

**Comment by Vineg** [comment]
And what about adaptive camera model fitting, did you tried it?

**Comment by s1ddok** [comment]
@Vineg I've sent you a separate archive with photos that reproduce this (though I'm on Metashape 2.0.4) but I can send it one more time.

> And what about adaptive camera model fitting, did you tried it?

yup, setting `adaptive_fitting=True` resulted in every calib parameter to be always zero (k1-k3, p1, p2)

**Comment by s1ddok** [comment]
@Vineg I've played with the new script -- it's definitely better! The dataset I've sent you now sometimes fully converges without an error (2/5 runs were successful) however I still sometimes get bad allocation on this dataset on 1-2 photo and 2-3 photos on other dataset. with each new fix it gets better. do you think we can push it further?

**Comment by s1ddok** [comment]
soooo, I just made few runs with the latest version -- works like a charm! cool! I hope other will benefit from it as well. I'll close it for now but will continue experiments, maybe it will reproduce on other sets.

thank you for your cooperation and quick patches!

**Comment by s1ddok** [comment]
@Vineg @PolarNick239 I've started training stuff using latest exports and unfortunately I have to report that reconsutrction quality in 3DGS reduced dramatically, even though more images get exported now on average. I've rolled back on previous version that I was using and it works great. do you think we can have best of two worlds? or maybe there is still a bug? i think that extrinsics changing might be an issue

**Comment by PolarNick239** [comment]
Please share a data-reproducer to [support@agisoft.com](mailto:support@agisoft.com) - share a Metashape project in zip-archive + photos, so that steps to reproduce will be:
1) Open Metashape project
2) Run script (old or new version)
3) Run GS (ideally: tell us what GS do you use and what parameters do you use - f.e. you can take screenshot of parameters)

Also, please provide us (via email or here) screenshots to demonstrate difference between both results - screenshot of the GS results after the old script usage and screenshot of (nearly) the same view of GS results with the new script (so that we will be certain that we are looking at the same problem).

Finally, please clarify which git script revisions (both - old and new) you are using so we can reproduce the problem in the closest to your conditions.

**Comment by Vineg** [comment]
@s1ddok

I've just fixed a mistake in calculation of projection coordinates. I don't know if these values are used somehow.
Camera poses and calibrations seems to be correct: if you open project in colmap and pick some valid tie points - reprojection error is low enough.

Adjusting camera rotation is ok, since we compensate it using perspective transformation. You can disable it though by commenting out this line: https://github.com/agisoft-llc/metashape-scripts/blob/43b3d9abf1d9df4821625a90b0b1fe4f4f0c9547/src/export_for_gaussian_splatting.py#L341

**Comment by PolarNick239** [comment]
@s1ddok feel free to re-open if you encounter the issue again :)
